'use client';
import {useEffect,useState} from 'react';
export default function Admin(){
 const [data,setData]=useState<any>(null); const [pending,setPending]=useState<any>(null); const [msg,setMsg]=useState('');
 async function load(){const a=await fetch('/api/admin/overview'); const b=await fetch('/api/admin/approvals'); setData(a.ok?await a.json():null); setPending(b.ok?await b.json():null)}
 useEffect(()=>{load()},[]);
 async function act(url:string,body:any){const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}); const d=await r.json(); setMsg(r.ok?'Updated successfully':d.error||'Action failed'); load()}
 return <main className="section"><div className="container"><div className="pageHead"><div><div className="eyebrow">CAROCAR ADMIN</div><h1>Operations dashboard</h1><p className="muted">Approve listings and documents, monitor bookings and payment totals.</p></div><button className="btn ghost" onClick={load}>Refresh</button></div>{msg&&<div className="notice">{msg}</div>}
 {data?<div className="statgrid">{[['Users',data.users],['Pending listings',data.listings],['Dealer approvals',data.dealers],['Rental bookings',data.rentals],['Saathi requests',data.rides],['Open reports',data.reports],['Pending documents',data.docs],['Paid volume',`₹${Number(data.revenue).toLocaleString('en-IN')}`]].map(x=><div className="stat" key={x[0]}><span className="muted">{x[0]}</span><strong>{x[1]}</strong></div>)}</div>:<div className="panel">Login as admin to view operations.</div>}
 {pending&&<div className="grid2" style={{marginTop:24}}><div className="panel"><h2>Owner listings</h2>{pending.owners.length?pending.owners.map((x:any)=><div className="row" key={x.id}><div><b>{x.vehicle.brand} {x.vehicle.model}</b><div className="muted">{x.vehicle.location} · ₹{x.vehicle.price.toLocaleString('en-IN')}</div></div><div><button className="btn primary" onClick={()=>act('/api/admin/approvals/listing',{type:'OWNER',id:x.id,status:'APPROVED'})}>Approve</button> <button className="btn ghost" onClick={()=>act('/api/admin/approvals/listing',{type:'OWNER',id:x.id,status:'REJECTED'})}>Reject</button></div></div>):<p className="muted">No pending owner listings.</p>}</div>
 <div className="panel"><h2>Dealer inventory</h2>{pending.dealers.length?pending.dealers.map((x:any)=><div className="row" key={x.id}><div><b>{x.vehicle.brand} {x.vehicle.model}</b><div className="muted">{x.dealer.storeName}</div></div><div><button className="btn primary" onClick={()=>act('/api/admin/approvals/listing',{type:'DEALER',id:x.id,status:'APPROVED'})}>Approve</button> <button className="btn ghost" onClick={()=>act('/api/admin/approvals/listing',{type:'DEALER',id:x.id,status:'REJECTED'})}>Reject</button></div></div>):<p className="muted">No pending dealer inventory.</p>}</div>
 <div className="panel"><h2>Documents</h2>{pending.docs.length?pending.docs.map((x:any)=><div className="row" key={x.id}><div><b>{x.type}</b><div className="muted">{x.user.profile?.name||x.user.phone} · <a href={x.storageKey} target="_blank">Open file</a></div></div><div><button className="btn primary" onClick={()=>act('/api/admin/approvals/document',{id:x.id,status:'VERIFIED'})}>Verify</button> <button className="btn ghost" onClick={()=>act('/api/admin/approvals/document',{id:x.id,status:'REJECTED'})}>Reject</button></div></div>):<p className="muted">No pending documents.</p>}</div>
 <div className="panel"><h2>Production connectors</h2><p className="muted">Payments support Razorpay when RAZORPAY_KEY_ID/SECRET and webhook secret are configured; otherwise local mock mode is available for testing. OTP is local-testable and can be connected to an SMS provider through the OTP provider hook. Uploaded documents are stored under public/uploads for local testing.</p></div></div>}
 </div></main>
}
