const { PrismaClient } = require('@prisma/client'); const { randomBytes, scryptSync } = require('crypto');
const db=new PrismaClient(); function hash(p){const s=randomBytes(16).toString('hex');return `${s}:${scryptSync(p,s,64).toString('hex')}`;}
async function main(){
 await db.platformFee.createMany({data:['BUY','SELL','RENT','SAATHI'].map(service=>({service,enabled:false,percentage:0,fixedFee:0})) ,skipDuplicates:true});
 const admin=await db.user.upsert({where:{email:'admin@carocar.in'},update:{role:'ADMIN'},create:{email:'admin@carocar.in',passwordHash:hash('carocar123'),role:'ADMIN',profile:{create:{name:'CarOcar Admin',city:'Pune'}}}});
 const demo=await db.user.upsert({where:{email:'demo@carocar.in'},update:{},create:{email:'demo@carocar.in',passwordHash:hash('carocar123'),profile:{create:{name:'Demo User',city:'Pune'}}}});
 const dealerUser=await db.user.upsert({where:{email:'dealer@carocar.in'},update:{},create:{email:'dealer@carocar.in',passwordHash:hash('carocar123'),role:'DEALER',profile:{create:{name:'ABC Motors',city:'Pune'}}}});
 const dealer=await db.dealer.upsert({where:{userId:dealerUser.id},update:{verification:'VERIFIED'},create:{userId:dealerUser.id,storeName:'ABC Motors',slug:'abc-motors',verification:'VERIFIED',address:'Pune, Maharashtra',contactPhone:'+91 98765 43210'}});
 const specs=[['Hyundai','Creta SX',2022,42000,1120000,'Pune','PETROL','AUTOMATIC','SUV'],['Hyundai','Creta SX',2022,35000,1175000,'Pune','PETROL','MANUAL','SUV'],['Kia','Seltos HTX',2023,18500,1590000,'Mumbai','DIESEL','AUTOMATIC','SUV'],['Tata','Nexon EV Max',2023,21000,1460000,'Pune','EV','AUTOMATIC','SUV'],['Toyota','Innova Crysta GX',2021,54000,1740000,'Nashik','DIESEL','MANUAL','MUV'],['Mahindra','XUV700 AX7',2022,35000,1875000,'Pune','DIESEL','AUTOMATIC','SUV']];
 for(let i=0;i<specs.length;i++){const [brand,model,year,km,price,loc,fuel,transmission,bodyType]=specs[i]; const v=await db.vehicle.create({data:{brand,model,variant:model.includes('SX')?'SX':undefined,registrationYear:year,owners:1,fuel,kmDriven:km,location:loc,price,transmission,bodyType,condition:'Good',description:'Verified sample listing for local exploration.',features:['ABS','Airbags','Reverse Camera']}}); if(i===1||i===2||i===4||i===5) await db.dealerInventory.create({data:{dealerId:dealer.id,vehicleId:v.id,status:'APPROVED',price,warranty:{months:6},inspection:{status:'Dealer inspected'}}}); else await db.ownerListing.create({data:{vehicleId:v.id,sellerId:demo.id,status:'APPROVED',negotiable:true}}); }
 const rental=await db.vehicle.create({data:{brand:'Maruti Suzuki',model:'Baleno',registrationYear:2023,owners:1,fuel:'PETROL',kmDriven:18000,location:'Pune',price:1800000,colour:'Blue'}}); await db.rentalListing.create({data:{vehicleId:rental.id,mode:'SELF_DRIVE',hourlyRate:250,dailyRate:1800,securityDeposit:5000,terms:'Valid licence and ID required.'}});
 const rideDate=new Date(); rideDate.setDate(rideDate.getDate()+1); const departure=new Date(rideDate); departure.setHours(8,0,0,0); await db.saathiRide.create({data:{driverId:dealerUser.id,fromLocation:'Pune',toLocation:'Mumbai',date:rideDate,departureAt:departure,pickupPoint:'Hinjewadi',dropPoint:'Andheri',availableSeats:3,contributionPerSeat:450,notes:'Demo carpool ride'}});
 console.log('Seeded. Demo login: demo@carocar.in / carocar123'); console.log('Admin login: admin@carocar.in / carocar123'); }
main().catch(e=>{console.error(e);process.exit(1)}).finally(()=>db.$disconnect());
